version: '3.8'
services:
    baselines:
        build: ../../.
        ports:
          - 9899:9899
          - 9898:9898
          - 9896:9896
          - 9895:9895
          - 9894:9894
          - 9893:9893
        volumes:
            - ../../:/app
        command: sjmz --nodocker host --files mcts.json dmcts.json random.json dmcts-50.json dmcts-large.json mcts-large.json
