version: '3.8'
services:
    baselines:
        build: ../../.
        network_mode: "host"
        volumes:
            - ../../:/app
        command: sjmz --nodocker host --files mcts.json dmcts.json random.json dmcts-50.json dmcts-large.json mcts-large.json
