version: '3.8'
services:
    mu_zero:
        image: ghcr.io/andrinbuerli/jass_mu_zero_mu_zero:latest
        network_mode: "host"
        volumes:
            - .:/app
        environment:
          - PYTHONPATH=/app:/app/extern/jass_gym
        deploy:
          resources:
            reservations:
              devices:
                - driver: nvidia
                  device_ids: ['0']
                  capabilities: [gpu]

