version: '3.8'
services:
    mu_zero:
        build:
          context: .
          network: "host"
        volumes:
            - .:/app
        deploy:
          resources:
            reservations:
              devices:
                - driver: nvidia
                  device_ids: ['0']
                  capabilities: [gpu]
        networks:
          - net
networks:
  net:
    external: true
    name: jass_net

