version: '3.8'
services:
    mu_zero:
        build:
          context: .
          network: "host"
        network_mode: "host"
        volumes:
            - .:/app
        environment:
          - PYTHONPATH=/app:/app/extern/jass_gym
        deploy:
          resources:
            reservations:
              devices:
                - driver: nvidia
                  device_ids: ['0']
                  capabilities: [gpu]

