version: '3.8'
services:
    mu_zero:
        build:
          context: .
          network: "host"
        volumes:
            - .:/app
        ports:
          - 8080:8080
        deploy:
          resources:
            reservations:
              devices:
                - driver: nvidia
                  device_ids: ['0']
                  capabilities: [gpu]


