version: '2.3'
services:
    data_collector0:
        image: ghcr.io/andrinbuerli/jass_mu_zero_mu_zero:latest
        volumes:
            - ../../:/app
        network_mode: host
        environment:
          - PYTHONPATH=/app:/app/extern/jass_gym
        command: >
            bash -c "sjmz --nodocker collect
            --host http://10.176.129.55
            --max_parallel_processes 50
            --max_parallel_threads 2
            --min_states_to_send 1"

