version: '2.3'
services:
    data_collector0:
        build:
            context: ../../
            network: "host"
        volumes:
            - ../../:/app
        network_mode: host
        environment:
          - PYTHONPATH=/app:/app/extern/jass_gym
        command: >
            bash -c "sjmz --nodocker collect
            --host http://localhost
            --max_parallel_processes 10
            --max_parallel_threads 2
            --continuous_games_without_reload 4
            --min_states_to_send 1"
         

