version: '2.3'
services:
    data_collector0:
        build: ../../
        volumes:
            - ../../:/app
        network_mode: host
        command: >
            bash -c "sjmz --nodocker --collect
            --host http://10.180.39.13
            --max_parallel_processes 10
            --max_parallel_threads 2
            --continuous_games_without_reload 4
            --min_states_to_send 1"
         

