version: '3.8'
services:
    data_collector0:
        image: ghcr.io/andrinbuerli/jass_mu_zero_mu_zero:latest
        volumes:
            - ../../:/app
        network_mode: host
        environment:
            - PYTHONPATH=/app:/app/extern/jass_gym
        command: >
            bash -c "sjmz --nodocker --collect
            --host http://10.180.39.13
            --max_parallel_processes 32
            --min_states_to_send 1"
        deploy:
          resources:
            reservations:
              devices:
                - driver: nvidia
                  device_ids: ['0']
                  capabilities: [gpu]


    data_collector1:
        image: ghcr.io/andrinbuerli/jass_mu_zero_mu_zero:latest
        volumes:
            - ../../:/app
        network_mode: host
        environment:
            - PYTHONPATH=/app:/app/extern/jass_gym
        command: >
            bash -c "sjmz --nodocker --collect
            --host http://10.180.39.13
            --max_parallel_processes 32
            --min_states_to_send 1"
        deploy:
          resources:
            reservations:
              devices:
                - driver: nvidia
                  device_ids: ['1']
                  capabilities: [gpu]
