version: '2.3'
services:
    data_collector0:
        build: ../../
        volumes:
            - ../../:/app
        environment:
            - NVIDIA_VISIBLE_DEVICES=0
        network_mode: host
        command: >
            bash -c "sjmz --nodocker --collect
            --host http://10.180.39.13
            --max_parallel_processes 6
            --max_parallel_threads 16
            --min_states_to_send 1"



    data_collector1:
        build: ../../
        volumes:
            - ../../:/app
        environment:
            - NVIDIA_VISIBLE_DEVICES=1
        network_mode: host
        command: >
            bash -c "sjmz --nodocker --collect
            --host http://10.180.39.13
            --max_parallel_processes 6
            --max_parallel_threads 16
            --min_states_to_send 1"
